### ISSUE TITLE
Pinch and rotation can not be recognized

### ISSUE THREAD

**Issue by my-fish** [longseespace/react-native-hammerjs#2] opened 2016-07-27 02:21 UTC
In the example ReactNativeHammerJSExample, the gestures pinch and rotation can not be recognized, both in iOS simulator and device.

**Comment by WillCoco** [comment] 2016-12-08 15:16
Pinch do not work on android ，rn 0.38

**Comment by longseespace** [comment] 2017-01-11 09:00
The issue is fixed for iOS in [`v2.0.11`](https://www.npmjs.com/package/react-native-hammerjs). I'm closing this issue.
Note: still doesn't work on Android due to this bug: [https://github.com/facebook/react-native/issues/7221](https://github.com/facebook/react-native/issues/7221). Please head to [https://github.com/longseespace/react-native-hammerjs/issues/4](https://github.com/longseespace/react-native-hammerjs/issues/4) for Android-related issues

**Closed as completed by longseespace** 2017-01-11 09:00 UTC
Labels: bug
